Issue 967
Magickbase/godwoken_explorer pull request #1025
Opened 2022-09-29 07:48 UTC by Naupio

2022-10-12 08:49 UTC, zmcNotafraid requested changes

2022-10-12 08:49 UTC, zmcNotafraid commented on lib/godwoken_indexer/block/sync_worker.ex
> +    else
else 不写也没问题把？

2022-10-12 08:49 UTC, zmcNotafraid commented on lib/godwoken_indexer/worker/erc721_erc1155_instance_metadata.ex
> +           Repo.get_by(TokenInstance,
这里这样一个个查效率太低，建议直接` where (token_contract_address_hash, token_id) IN ( (A, X), (B, Y), (C, Z) );` 统一提前过滤下

2022-10-14 02:28 UTC, Naupio commented on lib/godwoken_indexer/block/sync_worker.ex
> +    else
fixed

2022-10-16 11:09 UTC, Naupio commented on lib/godwoken_indexer/worker/erc721_erc1155_instance_metadata.ex
> +           Repo.get_by(TokenInstance,
added precheck

2022-10-17 02:11 UTC, zmcNotafraid requested changes

2022-10-17 02:11 UTC, zmcNotafraid commented on lib/godwoken_indexer/worker/erc721_erc1155_instance_metadata.ex
> +  def check_token_instance_retrieved(%{
这个方法没看到在哪使用？

2022-10-17 02:42 UTC, Naupio commented on lib/godwoken_indexer/worker/erc721_erc1155_instance_metadata.ex
> +  def check_token_instance_retrieved(%{
deleted unused function

2022-10-17 03:28 UTC, zmcNotafraid approved these changes

2022-10-20 07:42 UTC, FrederLu approved these changes

2022-10-20 07:42 UTC, merged