Feat: add retry woker for erc721/erc1155 fetch name/symbol
Magickbase/godwoken_explorer pull request #1100
Opened 2022-10-19 01:55 UTC by Naupio

## What problem does this PR solve?
link: #1087 

add retry woker for erc721/erc1155 fetch name/symbol if the first time fetch fail

## Check List

#### Test
- unit test
#### Task
 - none

2022-10-19 02:36 UTC, zmcNotafraid requested changes

2022-10-19 02:36 UTC, zmcNotafraid commented on lib/godwoken_indexer/worker/erc721_erc1155_udt_info_retry_worker.ex
> +    unique: [period: 7 * 24 * 60 * 60]
这里的unique 应该用 fields: [:args], 只需要保证合约地址唯一即可

2022-10-20 04:02 UTC, Naupio commented on lib/godwoken_indexer/worker/erc721_erc1155_udt_info_retry_worker.ex
> +    unique: [period: 7 * 24 * 60 * 60]
use ` unique: [fields: [:args]]` replace it

2022-10-20 09:36 UTC, FrederLu commented
Need to process historical data.

2022-10-26 01:59 UTC, zmcNotafraid approved these changes

2022-10-26 08:34 UTC, Keith-CY approved these changes

2022-10-31 04:26 UTC, FrederLu approved these changes

2022-10-31 04:26 UTC, merged