fix: Sourcify worker duplicate job casue performance problem of pg (issue-1156)
Magickbase/godwoken_explorer pull request #1185
Opened 2022-11-30 01:13 UTC by Naupio

## What problem does this PR solve?
link issue: #1156 
fix SmartContractRegister produce duplicate Sourcify-worker for registering which blocking job queue 
## Check List
- check  smart contract register work automatically
- check sourcify-worker is working
#### Test
- unit test
#### Task
 - none

2022-11-30 07:49 UTC, zmcNotafraid requested changes

2022-11-30 07:49 UTC, zmcNotafraid commented on lib/godwoken_indexer/worker/smart_contract_register.ex
> +defmodule GodwokenIndexer.Workers.SmartContractRegister do
```suggestion
defmodule GodwokenIndexer.Worker.SmartContractRegister do
```

2022-11-30 07:49 UTC, zmcNotafraid commented on lib/godwoken_indexer/worker/smart_contract_register.ex
> +    # oban open community version, need insert one by one to avoid duplicate job
each 不是 one_by_one 吗？

2022-11-30 07:49 UTC, zmcNotafraid commented on lib/godwoken_indexer/worker/sourcify.ex
> +  use Oban.Worker, queue: :default, unique: [period: :infinity, states: Oban.Job.states()]
加这个就够了把？

2022-11-30 08:38 UTC, Naupio commented on lib/godwoken_indexer/worker/smart_contract_register.ex
> +    # oban open community version, need insert one by one to avoid duplicate job
each 是的啊, 只是这里有话一下 并发 insert 进取, 增加一下备注说明

2022-12-01 06:37 UTC, Naupio commented on lib/godwoken_indexer/worker/smart_contract_register.ex
> +defmodule GodwokenIndexer.Workers.SmartContractRegister do
fixed

2022-12-01 06:46 UTC, zmcNotafraid approved these changes

2022-12-03 02:01 UTC, FrederLu approved these changes

2022-12-03 02:53 UTC, merged