Feat: add search combine udt api(issue-1161)
Magickbase/godwoken_explorer pull request #1198
Opened 2022-12-05 01:30 UTC by Naupio

## What problem does this PR solve?
link issue: #1161 
add combine search udt graphql api
## Check List
- search_udt
#### Test
- unit test
#### Task
 - none

2022-12-06 07:29 UTC, zmcNotafraid requested changes

2022-12-06 07:29 UTC, zmcNotafraid commented on lib/godwoken_explorer/block.ex
> +    last_finalized_block_number =
需要rebase，和你的代码无关

2022-12-06 09:14 UTC, FrederLu commented
@Naupio 
Now "type": "NATIVE" in the interface, but it seems that ERC20/ERC72/ERC1555 needs to be displayed. Do you want to obtain relevant information through other interfaces?
<img width="634" alt="image" src="https://user-images.githubusercontent.com/25676576/205869431-d63b6d39-1d4e-4c38-b53d-5da4c51aea1e.png">
<img width="574" alt="image" src="https://user-images.githubusercontent.com/25676576/205869703-bef7827a-ad26-4cd0-bde0-2bc631fbfdc1.png">

2022-12-06 09:39 UTC, Naupio commented on lib/godwoken_explorer/block.ex
> +    last_finalized_block_number =
fixed

2022-12-06 10:09 UTC, Naupio commented
> @Naupio 1、Now "type": "NATIVE" in the interface, but it seems that ERC20/ERC721/ERC1555 needs to be displayed. Do you want to obtain relevant information through other interfaces? <img alt="image" width="634" src="https://user-images.githubusercontent.com/25676576/205869431-d63b6d39-1d4e-4c38-b53d-5da4c51aea1e.png"> <img alt="image" width="574" src="https://user-images.githubusercontent.com/25676576/205869703-bef7827a-ad26-4cd0-bde0-2bc631fbfdc1.png">
> 
> 2、Prompt 500 with cursor request. <img alt="image" width="1133" src="https://user-images.githubusercontent.com/25676576/205873409-e39c939a-a438-4ce4-a1d7-75c3165de715.png"> <img alt="image" width="883" src="https://user-images.githubusercontent.com/25676576/205873481-0f2d9cc3-13ff-45c7-a603-adf6974781be.png">

add eth_type now
```graphql
query {
  search_udt(input: { fuzzy_name: "%ERC%", limit: 1 }) {
    entries {
      id
      icon
      name
      symbol
      type
      eth_type
      contract_address_hash
    }
    metadata {
      total_count
      before
      after
    }
  }
}
```
```json
{
  "data": {
    "search_udt": {
      "entries": [
        {
          "contract_address_hash": "0xd8114ef1af2b1b4f9953ae764977c7c4ed409ea1",
          "eth_type": "ERC20",
          "icon": null,
          "id": 89222,
          "name": "ERC20Demo",
          "symbol": "ERC",
          "type": "NATIVE"
        }
      ],
      "metadata": {
        "after": "g3QAAAABaAJkAARkZXNjZAACaWRiAAFchg==",
        "before": null,
        "total_count": 720
      }
    }
  }
}
```

2022-12-07 01:48 UTC, zmcNotafraid approved these changes

2022-12-07 04:07 UTC, FrederLu commented
@Naupio 
`eth_type` has been added, but the request with a cursor still prompts 500.

2022-12-07 04:28 UTC, Naupio commented
> @Naupio `eth_type` has been added, but the request with a cursor still prompts 500.

fixed and added more test case

2022-12-07 05:29 UTC, FrederLu approved these changes

2022-12-07 06:05 UTC, merged