feat: optimize log object with batch and dataloader(issue-1184)
Magickbase/godwoken_explorer pull request #1203
Opened 2022-12-07 02:35 UTC by Naupio

## What problem does this PR solve?
link #1184 
optimize log object with batch and dataloader

this pr depend on #1202
## Check List
- log object with udt subfeild
- log object with transaction subfield
- log object with smart_contract subfield
#### Test
- unit test
#### Task
 - none

2022-12-07 10:02 UTC, zmcNotafraid requested changes

2022-12-07 10:02 UTC, zmcNotafraid commented on lib/godwoken_explorer/graphql/types/account.ex
> +    # field :smart_contract, :smart_contract do
clear these comment

2022-12-07 10:13 UTC, Naupio commented on lib/godwoken_explorer/graphql/types/account.ex
> +    # field :smart_contract, :smart_contract do
fixed

2022-12-07 10:20 UTC, Naupio commented
testnet-stg was deployed

2022-12-09 06:38 UTC, FrederLu approved these changes

2022-12-09 07:02 UTC, zmcNotafraid approved these changes

2022-12-09 07:02 UTC, merged