feat: refactor account_udt api
Magickbase/godwoken_explorer pull request #1297
Opened 2023-01-28 16:32 UTC by Naupio

## What problem does this PR solve?

## Check List
#### Test
- unit test
#### Task
 - none

2023-02-13 01:33 UTC, zmcNotafraid requested changes

2023-02-13 01:33 UTC, zmcNotafraid commented on test/graphql/account_udt_test.exs
> +                     %{"balance" => "6.666E-15"}
这里已经转换成string了怎么还是这种格式

2023-02-13 01:55 UTC, Naupio commented on test/graphql/account_udt_test.exs
> +                     %{"balance" => "6.666E-15"}
查了一下, absinthe 的 decimal 直接使用 Decimal 库, absinthe 对应的 serialize 部分直接 defdelegate Decimal 的 to string, 而 Decimal 的 to string 默认使用 scientific format 展示

2023-02-13 01:59 UTC, zmcNotafraid commented on test/graphql/account_udt_test.exs
> +                     %{"balance" => "6.666E-15"}
你这样返回前端，前端是不是还要再处理一次？
Decimal.to_string(:normal) 这样就可以搞定

2023-02-13 08:06 UTC, FrederLu commented
It is found that the output parameters of the new interface start from the 4th data `tx_count` and the data in the test environment are inconsistent.
```graphql
query {
	account_udt_holders(
		input: {
			udt_id: 375
			limit: 12
		}
	) {
		entries {
			bit_alias
			eth_address
			balance
			tx_count
		}
		metadata {
			after
			before
			total_count
		}
	}
}
```
https://v1.testnet.gwscan.com/zh-CN/token/375?tab=holders
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/25676576/218401808-c0b43e64-404f-473b-aea9-c65b4f86bdf3.png">

<img width="575" alt="image" src="https://user-images.githubusercontent.com/25676576/218403133-8e39c1e4-3f3d-4f6c-9967-65a718867904.png">

2023-02-15 08:55 UTC, zmcNotafraid approved these changes

2023-02-16 09:47 UTC, FrederLu approved these changes

2023-02-16 13:46 UTC, merged