fix: fix update method id/name worker
Magickbase/godwoken_explorer pull request #1305
Opened 2023-02-02 15:46 UTC by Naupio

## What problem does this PR solve?

## Check List
#### Test
- unit test
#### Task
 - none

2023-02-03 06:17 UTC, zmcNotafraid commented on lib/godwoken_explorer/ETS/smart_contracts.ex
> +    :ets.insert(GodwokenExplorer.ETS.SmartContracts, {k, v, now})
cache 这里推荐参考 godwoken_explorer/lib/godwoken_explorer/chain/cache 下的来写自带TTL

2023-02-03 06:27 UTC, zmcNotafraid commented on lib/godwoken_indexer/worker/check_update_transaction_method_id_name.ex
> +      where: p.input_size >= 10,
这里应该还能加个条件 ，smart contract 的 abi 不为空

2023-02-03 06:54 UTC, Naupio commented on lib/godwoken_indexer/worker/check_update_transaction_method_id_name.ex
> +      where: p.input_size >= 10,
> 这里应该还能加个条件 ，smart contract 的 abi 不为空

smart contract 的 abi 更新是存在有滞后性的, 有些情况得先更新 method id

2023-02-03 06:55 UTC, zmcNotafraid commented on lib/godwoken_indexer/worker/check_update_transaction_method_id_name.ex
> +      where: p.input_size >= 10,
ok 明白了， method_id 和 method_name  是分开处理的

2023-02-03 06:57 UTC, zmcNotafraid requested changes

2023-02-03 06:57 UTC, zmcNotafraid commented on test/godwoken_indexer/block/sync_worker_test.exs
> +  defp abi_contents() do
这个abi  有什么特殊的吗？还是就是erc20 的？ insert(:smart_contract) 默认就自带erc20 abi

2023-02-03 06:59 UTC, Naupio commented on test/godwoken_indexer/block/sync_worker_test.exs
> +  defp abi_contents() do
找了 freder 之前测试的 smart contract 例子对应的 abi 放在测试用例里面用的, 不是特殊的

2023-02-03 07:00 UTC, Naupio commented on lib/godwoken_explorer/ETS/smart_contracts.ex
> +    :ets.insert(GodwokenExplorer.ETS.SmartContracts, {k, v, now})
MapCache 吗? 参考调整一下

2023-02-03 07:00 UTC, zmcNotafraid commented on test/godwoken_indexer/block/sync_worker_test.exs
> +  defp abi_contents() do
1. 如果只是erc20 就不用单独写这个方法了，
2. 如果是特殊的，把他放进test/support 文件下，参考erc20_abi.json

2023-02-03 07:15 UTC, Naupio commented on test/godwoken_indexer/block/sync_worker_test.exs
> +  defp abi_contents() do
这个是 erc721 contract 对应的 abi, 我加上去 support 里面吧

2023-02-03 07:55 UTC, FrederLu approved these changes

2023-02-06 15:28 UTC, Naupio commented on lib/godwoken_explorer/ETS/smart_contracts.ex
> +    :ets.insert(GodwokenExplorer.ETS.SmartContracts, {k, v, now})
add here https://github.com/Magickbase/godwoken_explorer/pull/1305/commits/51924dcc04e9ae94166dd0964313c11ab23a10ed

2023-02-06 15:29 UTC, Naupio commented on test/godwoken_indexer/block/sync_worker_test.exs
> +  defp abi_contents() do
fixed https://github.com/Magickbase/godwoken_explorer/pull/1305/commits/51924dcc04e9ae94166dd0964313c11ab23a10ed

2023-02-07 03:04 UTC, zmcNotafraid approved these changes

2023-02-07 03:05 UTC, merged