Issue 1284 2
Magickbase/godwoken_explorer pull request #1345
Opened 2023-03-06 01:37 UTC by Naupio

## What problem does this PR solve?
depend on pr: https://github.com/Magickbase/godwoken_explorer/pull/1344
## Check List
#### Test
- unit test
#### Task
 - none

2023-03-06 03:44 UTC, zmcNotafraid requested changes

2023-03-06 03:44 UTC, zmcNotafraid commented on lib/mix/tasks/update_erc721_token.ex
> +defmodule Mix.Tasks.UpdateErc721Token do
你这样遍历整个 token_transfers 数据太多了，你不如这样：先从udt 找到所有的erc721， 然后去token_transfer 查询每一个token 最后一条记录，distinct( :token_id) 然后再插入数据到 ERC721Token

2023-03-08 03:53 UTC, Naupio commented on lib/mix/tasks/update_erc721_token.ex
> +defmodule Mix.Tasks.UpdateErc721Token do
updated with https://github.com/Magickbase/godwoken_explorer/pull/1345/commits/ae743ec8593ad2cd8ca531ad7ea29e50610d1d0a

2023-03-13 02:12 UTC, zmcNotafraid approved these changes

2023-03-13 02:22 UTC, merged