Issue 1330
Magickbase/godwoken_explorer pull request #1394
Opened 2023-03-28 08:00 UTC by Naupio

## What problem does this PR solve?
issue: #1330 
- add sourcify metadata for smart contract
- fix sourcify process worker
- add new field sourcify metadata of  smart contract object 
- add testing code
- add history process task
## Check List
- smart contract with sourcify metadate
- history data was process
- auto worker process correct when smart contract register
#### Test
- unit test
#### Task
 - none

2023-03-28 09:48 UTC, zmcNotafraid requested changes

2023-03-28 09:48 UTC, zmcNotafraid commented on lib/godwoken_explorer/graphql/sourcify.ex
> +defmodule GodwokenExplorer.Graphql.SourcifyExport do
这里起个新文件不更好吗

2023-03-28 09:48 UTC, zmcNotafraid commented on lib/godwoken_explorer/smart_contract.ex
> +    field :sourcify_metadata, {:array, :map}
你这里明显是再创建一张表，然后1对多的关系绑定。
参考下 blockscout 怎么设计的

2023-03-29 02:53 UTC, Naupio commented on lib/godwoken_explorer/graphql/sourcify.ex
> +defmodule GodwokenExplorer.Graphql.SourcifyExport do
fixed

2023-03-29 02:54 UTC, Naupio commented on lib/godwoken_explorer/smart_contract.ex
> +    field :sourcify_metadata, {:array, :map}
如讨论, 这里维持这种方式

2023-03-29 12:25 UTC, zmcNotafraid approved these changes

2023-04-04 09:06 UTC, FrederLu approved these changes

2023-04-05 00:07 UTC, merged