Feat: add dockerfile and compose file and  new configuration
Magickbase/godwoken_explorer pull request #394
Opened 2022-04-19 07:48 UTC by Naupio

Draft PR

2022-04-21 06:24 UTC, zmcNotafraid commented
rebase main, 然后再env 里加这三个环境
  job: true,
  multiple_block_once: false,
  block_batch_size: 1

2022-04-27 05:48 UTC, zmcNotafraid requested changes

2022-04-27 05:48 UTC, zmcNotafraid commented on config/prod/testnet.exs
> +  temp_init_godwoken_l1_block_number: 2_286_200,
temp_init_godwoken_l1_block_number 和 eth_token_script_hash 可以删掉

2022-04-27 06:01 UTC, zmcNotafraid commented on config/runtime.exs
> +pg_show_sensitive_data_on_connection_error =
这个移除把

2022-04-27 06:03 UTC, zmcNotafraid commented on config/runtime.exs
> +pg_queue_interval = System.get_env("PG_QUEUE_INTERVAL", "2000") |> String.to_integer()
这个也移除

2022-04-27 06:04 UTC, zmcNotafraid commented on config/runtime.exs
> +pg_timeout = System.get_env("PG_TIMEOUT", "10000") |> String.to_integer()
这里再加一个connection_timeout

2022-04-27 08:03 UTC, Naupio commented on config/runtime.exs
> +pg_show_sensitive_data_on_connection_error =
这两个都有默认值的, 可以不填的, 但是本地开发有时候开隧道需要处理

2022-04-27 08:12 UTC, Naupio commented on config/prod/testnet.exs
> +  temp_init_godwoken_l1_block_number: 2_286_200,
done

2022-04-27 08:13 UTC, Naupio commented on config/runtime.exs
> +pg_queue_interval = System.get_env("PG_QUEUE_INTERVAL", "2000") |> String.to_integer()
done

2022-04-27 08:24 UTC, Naupio commented on config/runtime.exs
> +pg_timeout = System.get_env("PG_TIMEOUT", "10000") |> String.to_integer()
done

2022-04-27 16:01 UTC, merged

2022-04-28 01:35 UTC, zmcNotafraid commented on docker_compose/envs/.env
> +# GODWOKEN_JSON_RPC_URL=""
这里没必要注释掉，这都是必填的