Feat: add erc721 and erc1155 graphql api
Magickbase/godwoken_explorer pull request #893
Opened 2022-08-25 08:17 UTC by Naupio

2022-09-06 10:14 UTC, zmcNotafraid requested changes

2022-09-06 10:14 UTC, zmcNotafraid commented on lib/godwoken_explorer_web/endpoint.ex
> +  plug CORSPlug
这个地方不用修改吧

2022-09-06 10:14 UTC, zmcNotafraid commented on lib/godwoken_indexer/block/sync_worker.ex
> +      # conflict_target: [:address_hash, :token_contract_address_hash, :block_number]
注释删掉

2022-09-06 10:14 UTC, zmcNotafraid commented on lib/godwoken_indexer/fetcher/udt_balance.ex
> +    # {address_hash.bytes, token_contract_address_hash.bytes, block_number}
注释

2022-09-06 10:14 UTC, zmcNotafraid commented on lib/mix/tasks/update_udt_balance.ex
> +            if map[:token_id] do
这里没改啊 TODO

2022-09-13 06:02 UTC, Naupio commented on lib/godwoken_explorer/graphql/resolovers/token_transfer.ex
> +      |> where([tt], not is_nil(tt.token_ids) or not is_nil(tt.token_id))
add check  u.eth_type == :erc1155

2022-09-13 07:31 UTC, Naupio commented on lib/mix/tasks/update_udt_balance.ex
> +            if map[:token_id] do
fiexd https://github.com/Magickbase/godwoken_explorer/pull/893/commits/82e2ed050db9b280f625481eded3f1af3f5adf42

2022-09-15 06:33 UTC, Keith-CY approved these changes

2022-09-15 06:42 UTC, zmcNotafraid approved these changes

2022-09-15 06:43 UTC, merged