Fix: change 0x data to nil of method id
Magickbase/godwoken_explorer pull request #962
Opened 2022-09-14 01:01 UTC by Naupio

2022-09-14 03:05 UTC, Keith-CY commented
More test cases are desirable

1. `input` has a valid `method id` so a hex string of 8 bytes should be returned
2. `input` is not long enough to represent a `method id` so `null` is expected
3. transaction is not a contract call so `null` is expected

2022-09-14 07:24 UTC, zmcNotafraid requested changes

2022-09-14 07:24 UTC, zmcNotafraid commented on lib/godwoken_explorer/graphql/resolovers/transaction.ex
>      p =
这种地方直接Repo.get_by 就好了，为何还要用where

2022-09-14 07:24 UTC, zmcNotafraid commented on lib/godwoken_explorer/graphql/resolovers/transaction.ex
> +    case Repo.get(Account, to_account_id) do
这里改用  with condition，因为其余三种情况都是{:ok, nil}

2022-09-15 03:17 UTC, Naupio commented on lib/godwoken_explorer/graphql/resolovers/transaction.ex
>      p =
fixed https://github.com/Magickbase/godwoken_explorer/pull/962/commits/5557f510556c3718489f71dcfd2650f5564e908f

2022-09-15 03:17 UTC, Naupio commented on lib/godwoken_explorer/graphql/resolovers/transaction.ex
> +    case Repo.get(Account, to_account_id) do
fixed https://github.com/Magickbase/godwoken_explorer/pull/962/commits/5557f510556c3718489f71dcfd2650f5564e908f

2022-09-15 06:58 UTC, zmcNotafraid commented on lib/godwoken_explorer/graphql/resolovers/transaction.ex
> +         mid <- String.slice(input, 0, 10),
`length when length >= 10 <- input |> String.slice(0, 10) |> String.length()`

2022-09-15 07:01 UTC, zmcNotafraid approved these changes

2022-09-16 10:30 UTC, Keith-CY approved these changes

2022-09-16 16:11 UTC, merged